{% set name = "oauthenticator" %}
{% set version = "16.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e9d66df8621b98e802f91e4a9457395b68e93dac429fe1a436456147fe1391ef

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install --no-deps . -vv

requirements:
  host:
    - python >=3.8
    - pip
  run:
    # ref: https://github.com/jupyterhub/oauthenticator/blob/main/setup.py
    # ref: https://github.com/jupyterhub/oauthenticator/blob/main/requirements.txt
    - python >=3.8
    - jsonschema
    - jupyterhub >=1.2
    - requests
    - ruamel.yaml

test:
  imports:
    - oauthenticator

about:
  home: https://github.com/jupyterhub/oauthenticator
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: OAuth + JupyterHub Authenticator = OAuthenticator

  doc_url: https://jhubdocs.readthedocs.io/en/latest/oauthenticator/
  dev_url: https://github.com/jupyterhub/oauthenticator

extra:
  recipe-maintainers:
    - ericcina
    - sodre
    - consideRatio
