{% set name = "oauthenticator" %}
{% set version = "16.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 40c75d18951f69f5e80713028e5c75947e396b805a6f700fe23f0fc7b27161a4

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install --no-deps . -vv

requirements:
  host:
    - python >=3.8
    - pip
  run:
    # ref: https://github.com/jupyterhub/oauthenticator/blob/main/setup.py
    # ref: https://github.com/jupyterhub/oauthenticator/blob/main/requirements.txt
    - python >=3.8
    - jsonschema
    - jupyterhub >=2.2
    - pyjwt >=2
    - requests
    - ruamel.yaml
    - tornado
    - traitlets

test:
  imports:
    - oauthenticator

about:
  home: https://github.com/jupyterhub/oauthenticator
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: OAuth + JupyterHub Authenticator = OAuthenticator

  doc_url: https://jhubdocs.readthedocs.io/en/latest/oauthenticator/
  dev_url: https://github.com/jupyterhub/oauthenticator

extra:
  recipe-maintainers:
    - ericcina
    - sodre
    - consideRatio
